default_forbidden_words: []
default_request_frequency: 0.2
default_rest_time:
- 23
- 8
default_update_interval: 3
path_to_telegram_config: config/telegram_config_public.yaml
path_to_telegram_reply_dict: config/telegram_reply_dictionary.yaml
token: 111111111:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
